// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calcDistance
double calcDistance(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _smop_calcDistance(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(calcDistance(A, B));
    return rcpp_result_gen;
END_RCPP
}
// calcMOP
arma::vec calcMOP(arma::mat& x, arma::mat& y, arma::vec& prob);
RcppExport SEXP _smop_calcMOP(SEXP xSEXP, SEXP ySEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(calcMOP(x, y, prob));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_smop_calcDistance", (DL_FUNC) &_smop_calcDistance, 2},
    {"_smop_calcMOP", (DL_FUNC) &_smop_calcMOP, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_smop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
