# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name calcMOP
#' @title Compute mop serial version
#' @param x is the reference matrix.
#' @param y is the transfer matrix.
#' @return Returns a vector of mop values
#' @details The unique difference with the function parcalcMOP
#' is that it prints the percentage of advance
NULL

calcDistance <- function(A, B) {
    .Call('_smop_calcDistance', PACKAGE = 'smop', A, B)
}

calcMOP <- function(x, y, prob) {
    .Call('_smop_calcMOP', PACKAGE = 'smop', x, y, prob)
}

