# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Quantile
#' @title Helper function to estimate the quantile of a sample distribution
#' Returns a vector of the x values less or equal to the selected quantile
#' @details The function is taken from
#' https://github.com/RcppCore/Rcpp/issues/967
#' The authors are Rodney Sparapani and Dirk Eddelbuettel
NULL

#' @name calcMOP
#' @title Compute mop serial version
#' @param x is the reference matrix.
#' @param y is the trasnfer matrix.
#' @return Returns a vector of mop values
#' @details The unique difference with the function parcalcMOP
#' is that it prints the percentage of advance
NULL

calcDistance <- function(A, B) {
    .Call('_smop_calcDistance', PACKAGE = 'smop', A, B)
}

calcMOP <- function(x, y, prob) {
    .Call('_smop_calcMOP', PACKAGE = 'smop', x, y, prob)
}

